projectSyO/companys/urls.py
from django.urls import path

from companys.views import CompanyView, NationalCompanyListView, ForeignCompanyListView, \
    CompanyDetailView

urlpatterns = [
    path('empresa/<int:pk>', CompanyDetailView.as_view(), name='perfil-empresa'),
    path('nacionales', NationalCompanyListView.as_view(), name="empresas-nacionales"),
    path('extranjeras', ForeignCompanyListView.as_view(), name='empresas-extranjeras'),
    path('', CompanyView.as_view(), name='index'),

]

projectSyO/companys/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from locations.models import Country


class Company(models.Model):
    company_name = models.CharField(max_length=25)
    location = models.ForeignKey(Country, on_delete=models.CASCADE)
    address = models.CharField(max_length=45)
    phone = models.PositiveIntegerField()
    email = models.EmailField()
    work_experience = models.CharField(max_length=25,
                                       choices=(("1 a 3 años", "1 a 3 años"), ("3 a 6 años", "3 a 6 años"),
                                                ("6 a 15 años", "6 a 15 años"),
                                                ("15 en adelante", "15 en adelante")))

    question1 = models.CharField(max_length=250)
    answer1 = models.CharField(max_length=250)
    question2 = models.CharField(max_length=250)
    answer2 = models.CharField(max_length=250)
    question3 = models.CharField(max_length=250)
    answer3 = models.CharField(max_length=250)
    question4 = models.CharField(max_length=250)
    answer4 = models.CharField(max_length=250)
    question5 = models.CharField(max_length=250)
    answer5 = models.CharField(max_length=250)
    question6 = models.CharField(max_length=250)
    answer6 = models.CharField(max_length=250)
    question7 = models.CharField(max_length=250)
    answer7 = models.CharField(max_length=250)
    question8 = models.CharField(max_length=250)
    answer8 = models.CharField(max_length=250)
    question9 = models.CharField(max_length=250)
    answer9 = models.CharField(max_length=250)
    question10 = models.CharField(max_length=250)
    answer10 = models.CharField(max_length=250)
    question11 = models.CharField(max_length=250)
    answer11 = models.CharField(max_length=250)
    logo = models.ImageField()
    type = models.CharField(max_length=25, choices=(("Nacional", "Nacional"), ("Extranjeras", "Extranjeras")))
    grafica1 = models.ImageField()
    grafica2 = models.ImageField()

    class Meta:
        verbose_name = 'company'
        verbose_name_plural = 'companys'

    def __str__(self):
        return self.company_name

#
# class Certification(models.Model):
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     certification = models.CharField(max_length=45)
#
#     class Meta:
#         verbose_name = 'certification'
#         verbose_name_plural = 'certifications'
#
#     def __str__(self):
#         return self.certification
#
#
# class Question(models.Model):
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     question = models.CharField(max_length=250)
#
#     verbose_name = 'question'
#     verbose_name_plural = 'questions'
#
#     def __str__(self):
#         return self.question
#
#
# class Service(models.Model):
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     service_name = models.CharField(max_length=250)
#
#     class Meta:
#         verbose_name = 'service'
#         verbose_name_plural = 'services'
#
#     def __str__(self):
#         return self.service_name
#
#
# class Answer(models.Model):
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     answer = models.CharField(max_length=45)
#
#     class Meta:
#         verbose_name = 'answer'
#         verbose_name_plural = 'answers'
#
#     def __str__(self):
#         return self.answer
#
#
# class Client(models.Model):
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     name_client = models.CharField(max_length=100)
#
#     class Meta:
#         verbose_name = 'client'
#         verbose_name_plural = 'clients'
#
#     def __str__(self):
#         return self.name_client
#
#
# class Language(models.Model):
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     name_language = models.CharField(max_length=45)
#
#     class Meta:
#         verbose_name = 'language'
#         verbose_name_plural = 'languages'
#
#     def __str__(self):
#         return self.name_language

projectSyO/companys/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView

from companys.models import Company
from market.models import Offer, Demand


class CompanyView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['offers'] = Offer.objects.all()
        data['demands'] = Demand.objects.all()
        data['companys'] = Company.objects.all()
        return data


class NationalCompanyListView(ListView):
    template_name = 'empresas-nacionales.html'
    model = Company
    queryset = Company.objects.filter(type='Nacional')


class ForeignCompanyListView(ListView):
    template_name = 'empresas-extranjeras.html'
    model = Company
    queryset = Company.objects.filter(type='Extranjeras')


class CompanyDetailView(DetailView):
    template_name = 'perfiles-empresas.html'
    model = Company

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        pk_company = self.object
        data['offers'] = Offer.objects.filter(company__pk=pk_company.pk)
        data['demands'] = Demand.objects.filter(company__pk=pk_company.pk)
        return data

        # pk_company = self.object
        # data['offers'] = Offer.objects.all()
        # data['demandas'] = Demand.objects.all()
        # data['questions'] = Question.objects.filter(company__pk=pk_company.pk)
        # data['servicios'] = Service.objects.filter(company__pk=pk_company.pk)
        # data['answers'] = Answer.objects.filter(company__pk=pk_company.pk)
        # data['languajes'] = Language.objects.filter(company__pk=pk_company.pk)
        # data['certificacions'] = Certification.objects.filter(company__pk=pk_company.pk)
        # return data

projectSyO/companys/templates/empresas-extranjeras.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
		
		<link rel="shortcut icon" href="static/images/favicon.ico" type="image/x-icon">
		<link rel="icon" href="static/images/favicon.ico" type="image/x-icon">
        

        <title>Empresas Extranjeras</title>
        
        <!-- Bootstrap -->
        <link href="static/css/bootstrap.min.css" rel="stylesheet">
		
        <link href="static/css/fontawesome.css" rel="stylesheet">
        <link href="static/css/themify-icons.css" rel="stylesheet">
        <link href="static/css/magnific-popup.css" rel="stylesheet">
		
        <link href="static/css/animate.css" rel="stylesheet">
        <link href="static/css/owl.carousel.min.css" rel="stylesheet">
    
        
        <!-- Main css -->
        <link href="static/css/main.css" rel="stylesheet">
		
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
	
    <body>

    	<!-- Preloader -->
		<div class="preloader">
			<div class="spinner">
			   <span class="spinner-rotate"></span>
			</div>
		</div><!-- /Preloader -->
        
        <!-- Header Area -->
        <header class="main_menu_area">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<nav class="navbar navbar-expand-lg navbar-light">
{#							<a class="navbar-brand" href="index.html"><img src="static/images/logo.png" alt=""></a>#}
							<div class="mobile_toggle">
								<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
							</div>
							<div class="collapse navbar-collapse" id="navbarSupportedContent">
								<ul class="navbar-nav mr-auto">
									<li class="nav-item active"><a class="nav-link" href="/">Ofertas & Demandas</a></li>
									<li class="nav-item dropdown submenu">
										<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Empresas </a>
										<ul class="dropdown-menu">
											<li class="nav-item"><a class="nav-link" href="/extranjeras">Extranjeras</a></li>
											<li class="nav-item"><a class="nav-link" href="/nacionales">Nacionales</a></li>
										</ul>
									</li>
								</ul>
							</div>
						</nav>
					</div>
				</div>
			</div>
        </header><!-- Header Area -->
		
		<!--Custom Hero Area-->
		<section class="custom-hero dark-overlay" style="background: url(static/images/custom-hero-bg.jpg) no-repeat">
			<div class="container">
				<div class="row cl-white">
					<div class="col-lg-6 col-md-6">
						<div class="custom-hero-title">
							<h2>Empresas Extranjeras</h2>
						</div>
					</div>
				</div>
			</div>
		</section><!--/Custom Hero Area-->
		
		<!--Listing Grid Area-->
		<section class="listing-grid-area section-padding">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-md-6">
						<div class="row">
                            {% for company in company_list %}
							<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 wow fadeInUp" data-wow-delay="0.3s">
                                <div class="single-listing-directory">
	                                <img src="{{ company.logo.url }}" alt="{{ company.company_name }}">
	                                <div class="listing-directory-content">
                                		<a href="{% url 'perfil-empresa' company.pk %}"><h3>{{company.company_name}}</h3></a>
                                        <p><i class="fas fa-map-marker-alt"></i> {{ company.location.name }}, {{ company.location.city }}</p>
                                		<div class="listing-location">
                                			<i class="fa fa-address-book"></i>{{company.address}}
                                		</div>
                                		<div class="listing-contact">
                                			<i class="fa fa-phone"></i>{{company.phone}}
                                		</div>
	                                </div>
	                                <div class="directory-ratings">
	                                	<span><i class="fa fa-hotel"></i>Empresa Desarrolladora de Software</span>
                                        <span class="star-ratings">
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
                                        </span>
	                                </div>
                            	</div>
                            </div>
                            {% endfor %}
						</div>
					</div>
				</div>
			</div>
		</section><!--/Listing Grid Area-->

		
		<div class="copyright-text">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col centered">
						<p>&copy; 2020 Todos los derechos reservados &mdash; Creado por <a href=""> Yojan & Martha </a></p>
					</div>
				</div>
			</div>
		</div>


			
		
			
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="static/js/jquery-3.2.1.min.js"></script>
        <script src="static/js/jquery-migrate.js"></script>
        <script src="static/js/jquery-ui.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="static/js/popper.js"></script>
        <script src="static/js/bootstrap.min.js"></script>

		<script src="static/js/owl.carousel.min.js"></script>

        
        <script src="static/js/waypoints.min.js"></script>
        <script src="static/js/jquery.counterup.min.js"></script>
        <script src="static/js/scrollUp.min.js"></script>
        <script src="static/js/wow.min.js"></script>
        <script src="static/js/script.js"></script>
    </body>
</html>

projectSyO/companys/templates/empresas-nacionales.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
		
		<link rel="shortcut icon" href="static/images/favicon.ico" type="image/x-icon">
		<link rel="icon" href="static/images/favicon.ico" type="image/x-icon">
        

        <title>Empresas Nacionales</title>
        
        <!-- Bootstrap -->
        <link href="static/css/bootstrap.min.css" rel="stylesheet">
		
        <link href="static/css/fontawesome.css" rel="stylesheet">
        <link href="static/css/themify-icons.css" rel="stylesheet">
        <link href="static/css/magnific-popup.css" rel="stylesheet">
		
        <link href="static/css/animate.css" rel="stylesheet">
        <link href="static/css/owl.carousel.min.css" rel="stylesheet">
    
        
        <!-- Main css -->
        <link href="static/css/main.css" rel="stylesheet">
		
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
	
    <body>

    	<!-- Preloader -->
		<div class="preloader">
			<div class="spinner">
			   <span class="spinner-rotate"></span>
			</div>
		</div><!-- /Preloader -->
        
        <!-- Header Area -->
        <header class="main_menu_area">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<nav class="navbar navbar-expand-lg navbar-light">
{#							<a class="navbar-brand" href="index.html"><img src="static/images/logo.png" alt=""></a>#}
							<div class="mobile_toggle">
								<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								</button>
							</div>
							<div class="collapse navbar-collapse" id="navbarSupportedContent">
								<ul class="navbar-nav mr-auto">
									<li class="nav-item active"><a class="nav-link" href="/">Ofertas & Demandas</a></li>
									<li class="nav-item dropdown submenu">
										<a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										Empresas </a>
										<ul class="dropdown-menu">
											<li class="nav-item"><a class="nav-link" href="/extranjeras">Extranjeras</a></li>
											<li class="nav-item"><a class="nav-link" href="/nacionales">Nacionales</a></li>
										</ul>
									</li>
								</ul>
							</div>
						</nav>
					</div>
				</div>
			</div>
        </header><!-- Header Area -->
		
		<!--Custom Hero Area-->
		<section class="custom-hero dark-overlay" style="background: url(static/images/custom-hero-bg.jpg) no-repeat">
			<div class="container">
				<div class="row cl-white">
					<div class="col-lg-6 col-md-6">
						<div class="custom-hero-title">
							<h2>Empresas Nacionales</h2>
						</div>
					</div>
				</div>
			</div>
		</section><!--/Custom Hero Area-->
		
		<!--Listing Grid Area-->
		<section class="listing-grid-area section-padding">
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-md-6">
						<div class="row">
                            {% for company in company_list %}
							<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 wow fadeInUp" data-wow-delay="0.3s">
                                <div class="single-listing-directory">
	                                <img src="{{ company.logo.url }}" alt="{{ company.company_name }}">
	                                <div class="listing-directory-content">
                                		<a href="{% url 'perfil-empresa' company.pk %}"><h3>{{company.company_name}}</h3></a>
                                        <p><i class="fas fa-map-marker-alt"></i> {{ company.location.name }}, {{ company.location.city }}</p>
                                		<div class="listing-location">
                                			<i class="fa fa-address-book"></i>{{company.address}}
                                		</div>
                                		<div class="listing-contact">
                                			<i class="fa fa-phone"></i>{{company.phone}}
                                		</div>
	                                </div>
	                                <div class="directory-ratings">
	                                	<span><i class="fa fa-hotel"></i>Empresa Desarrolladora de Software</span>
                                        <span class="star-ratings">
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
			                                		<i class="fa fa-star"></i>
                                        </span>
	                                </div>
                            	</div>
                            </div>
                            {% endfor %}
						</div>
					</div>

				</div>
			</div>
		</section><!--/Listing Grid Area-->
        
		
		<div class="copyright-text">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col centered">
						<p>&copy; 2020 Todos los derechos reservados &mdash; Creado por <a href=""> Yojan & Martha </a></p>
					</div>
				</div>
			</div>
		</div>


			
		
			
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="static/js/jquery-3.2.1.min.js"></script>
        <script src="static/js/jquery-migrate.js"></script>
        <script src="static/js/jquery-ui.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="static/js/popper.js"></script>
        <script src="static/js/bootstrap.min.js"></script>

		<script src="static/js/owl.carousel.min.js"></script>

        
        <script src="static/js/waypoints.min.js"></script>
        <script src="static/js/jquery.counterup.min.js"></script>
        <script src="static/js/scrollUp.min.js"></script>
        <script src="static/js/wow.min.js"></script>
        <script src="static/js/script.js"></script>
    </body>
</html>